project_name: kink

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - id: linux-amd64
    binary: kink-linux-{{ .Arch }}
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/Trendyol/kink/cmd.GitVersion={{ .Version }} -X github.com/Trendyol/kink/cmd.gitCommit={{ .ShortCommit }}  -X github.com/Trendyol/kink/cmd.buildDate={{ .CommitDate }}
    no_unique_dist_dir: true

  - id: darwin-amd64
    binary: kink-darwin-{{ .Arch }}
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/Trendyol/kink/cmd.GitVersion={{ .Version }} -X github.com/Trendyol/kink/cmd.gitCommit={{ .ShortCommit }}  -X github.com/Trendyol/kink/cmd.buildDate={{ .CommitDate }}
    no_unique_dist_dir: true

  - id: windows-amd64
    binary: kink-windows-{{ .Arch }}
    main: ./main.go
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/Trendyol/kink/cmd.GitVersion={{ .Version }} -X github.com/Trendyol/kink/cmd.gitCommit={{ .ShortCommit }}  -X github.com/Trendyol/kink/cmd.buildDate={{ .CommitDate }}
      - -buildmode=exe
    no_unique_dist_dir: true

signs:
  - cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    args: ["sign-blob", "-key=cosign.key", "-output=${signature}", "${artifact}"]
    artifacts: binary

docker_signs:
  - artifacts: all
    args: [ "sign", "-key=cosign.key", "${artifact}" ]
    stdin: '{{ .Env.COSIGN_PASSWORD }}'

dockers:
  - image_templates: [ "ghcr.io/trendyol/{{ .ProjectName }}:{{ .Version }}-amd64" ]
    dockerfile: Dockerfile.goreleaser
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/Trendyol/kink
      - --label=org.opencontainers.image.source=https://github.com/Trendyol/kink
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

brews:
  - tap:
      owner: Trendyol
      name: homebrew-trendyol-tap
    homepage: https://github.com/trendyol
    description: KinK is a helper CLI that facilitates to manage KinD clusters as Kubernetes pods. Designed to ease clusters up for fast testing with batteries included in mind.
    license: MIT
    test: |
      system "#{bin}/kink version"
    dependencies:
      - name: go
        type: optional
      - name: git
    install: |-
      bin.install "kink"
      bash_completion.install "completions/kink.bash" => "kink"
      zsh_completion.install "completions/kink.zsh" => "_kink"
      fish_completion.install "completions/kink.fish"

archives:
  - format: binary
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch
release:
  github:
    owner: Trendyol
    name: kink
  extra_files:
    - glob: dist/*.sig