project_name: kink

env:
  - GO111MODULE=on
  - CGO_ENABLED=1

before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - id: linux-amd64
    binary: kink-linux-{{ .Arch }}
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0

  - id: darwin-amd64
    binary: kink-darwin-{{ .Arch }}
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    no_unique_dist_dir: true
    env:
      - CC=o64-clang
      - CXX=o64-clang++

  - id: windows-amd64
    binary: kink-windows-{{ .Arch }}
    main: ./main.go
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -buildmode=exe
      - "{{ .Env.LDFLAGS }}"
    no_unique_dist_dir: true
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
dockers:
  - image_templates: [ "registry.trendyol.com/platform/base/poc/kink:{{ .Tag }}" ]
    dockerfile: Dockerfile.goreleaser
    goos: linux
    goarch: amd64
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://gitlab.com/goreleaser/example
      - --label=org.opencontainers.image.source=https://gitlab.com/goreleaser/example
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
gomod:
  proxy: true
  env:
    - GOPRIVATE=gitlab.trendyol.com
archives:
  - format: tar.gz
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
    files:
      - README.md
      - LICENSE
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch
# .goreleaser.yml
gitlab_urls:
  api: https://gitlab.trendyol.com/api/v4/
  download: https://gitlab.trendyol.com
  skip_tls_verify: false
release:
  gitlab:
    owner: ""
    name: 8141
  disable: false
